### ISSUE TITLE
Intermittent fail

### ISSUE THREAD

**Issue by jan-sykora** [nolar/setup-k3d-k3s#22]
When running the setup-k3d-k3s in our Github workflow we sometimes get an error.

Setup:
```yaml
jobs:
  some-job:
    steps:
      - name: Set up k3d
         uses: nolar/setup-k3d-k3s@v1
         with:
           version: v1.20
```
Error:
```
Run nolar/setup-k3d-k3s@v1
  with:
    version: v1.20
    k3d-tag: latest
  env:
    MSYS: winsymlinks:nativestrict
Run /home/runner/work/_actions/nolar/setup-k3d-k3s/v1/action.sh
  /home/runner/work/_actions/nolar/setup-k3d-k3s/v1/action.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    MSYS: winsymlinks:nativestrict
    VERSION: v1.20
    K3D_TAG: latest
    K3D_NAME: 
    K3D_ARGS: 
    GITHUB_TOKEN: 
    SKIP_CREATION: 
    SKIP_READINESS: 
Error: Process completed with exit code 22.
```

Based on the exit code it seems that the curl command in action.sh got 401 Unauthorized. This error occurs irregularly (when running the same setup).
